// @ts-check
export default [
    ["empty", "empty", "empty", "empty", "start", "empty", "empty", "empty", "empty", "empty", "empty"],
    ["empty", "empty", "empty", "empty", "road" , "empty", "empty", "empty", "empty", "empty", "empty"],
    ["empty", "empty", "empty", "empty", "road" , "empty", "empty", "empty", "empty", "empty", "empty"],
    ["empty", "empty", "empty", "empty", "x"    , "road" , "road" , "road" , "x"    , "road" , "road" ],
    ["empty", "empty", "empty", "empty", "road" , "empty", "empty", "empty", "empty", "empty", "x"    ],
    ["empty", "empty", "empty", "empty", "road" , "empty", "empty", "empty", "empty", "empty", "x"    ],
    ["empty", "empty", "empty", "empty", "road" , "empty", "empty", "empty", "empty", "empty", "road" ],
    ["empty", "empty", "empty", "empty", "x"    , "empty", "empty", "empty", "empty", "empty", "road" ],
    ["road" , "x"    , "road" ,  "road",  "road", "x"    , "road" , "road" , "x"    , "road" , "road" ],
    ["road" , "empty", "empty", "empty", "road" , "empty", "empty", "empty", "empty", "empty", "empty"],
    ["x"    , "empty", "empty", "empty", "road" , "empty", "empty", "empty", "empty", "empty", "empty"],
    ["road" , "road" , "road" , "x"    , "road" , "empty", "empty", "empty", "empty", "empty", "empty"],
    ["empty", "empty", "empty", "empty", "road" , "empty", "empty", "empty", "empty", "empty", "empty"],
    ["empty", "empty", "empty", "empty", "x"    , "empty", "empty", "empty", "empty", "empty", "empty"],
    ["empty", "empty", "empty", "empty", "road" , "empty", "empty", "empty", "empty", "empty", "empty"],
    ["empty", "empty", "empty", "empty", "road" , "x"    , "road" , "road" , "x"    , "road" , "x"    ],
    ["empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "x"    ],
    ["empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "road" ],
    ["empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "x"    ],
    ["empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "road" ],
    ["empty", "empty", "empty", "empty", "empty", "x"    , "x"    , "road" , "road" , "x"    , "road" ],
    ["empty", "empty", "empty", "empty", "empty", "road" , "empty", "empty", "empty", "empty", "empty" ],
    ["empty", "empty", "empty", "empty", "empty", "win" , "empty", "empty", "empty", "empty", "empty" ],
]